skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tmmf = "BZVm6He91MdutTeAQFYqG8SxPt84vfkGwJULmAwMnb2E"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
